### ISSUE TITLE
python train.py --cfg_file cfgs/kitti_models/GLENet_VR2.yaml

### ISSUE THREAD

**Issue by 6Superman6** [Eaphan/GLENet#1]
epochs:   0%|                                                                             | 0/80 [00:05<?, ?it/s]
Traceback (most recent call last):                                                       | 0/928 [00:00<?, ?it/s]
  File "train.py", line 205, in <module>
    main()
  File "train.py", line 156, in main
    train_model(
  File "/home/dell/project/pcdet/GLENet-main/tools/train_utils/train_utils.py", line 133, in train_model
    accumulated_iter = train_one_epoch(
  File "/home/dell/project/pcdet/GLENet-main/tools/train_utils/train_utils.py", line 47, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/home/dell/project/pcdet/GLENet-main/tools/../pcdet/models/__init__.py", line 42, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/home/dell/anaconda3/envs/glenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dell/project/pcdet/GLENet-main/tools/../pcdet/models/detectors/voxel_rcnn.py", line 14, in forward
    loss, tb_dict, disp_dict = self.get_training_loss()
  File "/home/dell/project/pcdet/GLENet-main/tools/../pcdet/models/detectors/voxel_rcnn.py", line 29, in get_training_loss
    loss_rcnn, tb_dict = self.roi_head.get_loss(tb_dict)
  File "/home/dell/project/pcdet/GLENet-main/tools/../pcdet/models/roi_heads/roi_head_template.py", line 281, in get_loss
    rcnn_loss_reg, reg_tb_dict = self.get_box_reg_layer_loss(self.forward_ret_dict)
  File "/home/dell/project/pcdet/GLENet-main/tools/../pcdet/models/roi_heads/voxelrcnn_kl_label_iou_head.py", line 104, in get_box_reg_layer_loss
    label_var_log = torch.log(gt_uncertaintys_of_rois + 1e-10)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

**Comment by 6Superman6** [comment]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

**Comment by Eaphan** [comment]
Hi, did you replace the original info files with [kitti_infos_train.pkl](https://drive.google.com/file/d/1iQl3krptYDBfmLsQFR8xip4Wtl8jj-Uy/view?usp=sharing) and [kitti_dbinfos_train.pkl](https://drive.google.com/file/d/1bSmFeO3M4YgXsUG8qSfs_aPoXWXSPX3C/view?usp=sharing) that contain label uncertainty.

Besides, how do you make the config file cfgs/kitti_models/GLENet_VR2.yaml?

**Comment by 6Superman6** [comment]
GLENet_ VR2.yaml is the file I backed up. I have replaced these two files, but have reported new errors. Could you help me find out what is wrong?

The error is reported as follows:

 File "train.py", line 205, in <module>
    main()
  File "train.py", line 156, in main
    train_model(
  File "/home/dell/project/pcdet/GLENet-main/tools/train_utils/train_utils.py", line 133, in train_model
    accumulated_iter = train_one_epoch(
  File "/home/dell/project/pcdet/GLENet-main/tools/train_utils/train_utils.py", line 47, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/home/dell/project/pcdet/GLENet-main/tools/../pcdet/models/__init__.py", line 42, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/home/dell/anaconda3/envs/glenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dell/project/pcdet/GLENet-main/tools/../pcdet/models/detectors/voxel_rcnn.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/dell/anaconda3/envs/glenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dell/project/pcdet/GLENet-main/tools/../pcdet/models/roi_heads/voxelrcnn_kl_label_iou_head.py", line 47, in forward
    targets_dict = self.assign_targets(batch_dict)
  File "/home/dell/project/pcdet/GLENet-main/tools/../pcdet/models/roi_heads/roi_head_template.py", line 134, in assign_targets
    targets_dict = self.proposal_target_layer.forward(batch_dict)
  File "/home/dell/project/pcdet/GLENet-main/tools/../pcdet/models/roi_heads/target_assigner/proposal_target_layer.py", line 32, in forward
    batch_rois, batch_gt_of_rois, batch_roi_ious, batch_roi_scores, batch_roi_labels, batch_gt_uncertaintys_of_rois = self.sample_rois_for_rcnn(
  File "/home/dell/project/pcdet/GLENet-main/tools/../pcdet/models/roi_heads/target_assigner/proposal_target_layer.py", line 116, in sample_rois_for_rcnn
    sampled_inds = self.subsample_rois(max_overlaps=max_overlaps)
  File "/home/dell/project/pcdet/GLENet-main/tools/../pcdet/models/roi_heads/target_assigner/proposal_target_layer.py", line 170, in subsample_rois
    raise NotImplementedError
NotImplementedError

**Comment by 6Superman6** [comment]
> Hi, did you replace the original info files with [kitti_infos_train.pkl](https://drive.google.com/file/d/1iQl3krptYDBfmLsQFR8xip4Wtl8jj-Uy/view?usp=sharing) and [kitti_dbinfos_train.pkl](https://drive.google.com/file/d/1bSmFeO3M4YgXsUG8qSfs_aPoXWXSPX3C/view?usp=sharing) that contain label uncertainty.
> 
> Besides, how do you make the config file cfgs/kitti_models/GLENet_VR2.yaml?

GLENet_ VR2.yaml is the file I backed up. I have replaced these two files, but have reported new errors. Could you help me find out what is wrong?

The error is reported as follows:

**Comment by 6Superman6** [comment]
> GLENet_ VR2.yaml is the file I backed up. I have replaced these two files, but have reported new errors. Could you help me find out what is wrong?
> 
> The error is reported as follows:

GLENet_ VR2.yaml is the file I backed up. I have replaced these two files, but have reported new errors. Could you help me find out what is wrong?

The error is reported as follows:

raise NotImplementedError
NotImplementedError

**Comment by Eaphan** [comment]
I try to run the code in my own environment, and I do not meet the problem. Could you use the command "git status" to see the changes you made?

If you did not change any codes, is the error reproducible?

**Comment by 6Superman6** [comment]
> I try to run the code in my own environment, and I do not meet the problem. Could you use the command "git status" to see the changes you made?
> 
> If you did not change any codes, is the error reproducible?

Can I add your WeChat or QQ if it's convenient for you? This is my WeChat number: 15806409818. Thank you very much.

**Comment by 6Superman6** [comment]
> I try to run the code in my own environment, and I do not meet the problem. Could you use the command "git status" to see the changes you made?
> 
> If you did not change any codes, is the error reproducible?

Generate Label Uncertainties with GLEnet, step 1.0-1.2 in this step failed to run successfully. Is it related to this

**Comment by 6Superman6** [comment]
> I try to run the code in my own environment, and I do not meet the problem. Could you use the command "git status" to see the changes you made?
> 
> If you did not change any codes, is the error reproducible?


Thank you very much. I have solved the problem with your help.
