### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by mihui20** [Eaphan/GLENet#8]
Traceback (most recent call last):
  File "/home/mi/GLENet/tools/train.py", line 209, in <module>
    main()
  File "/home/mi/GLENet/tools/train.py", line 177, in main
    merge_all_iters_to_one_epoch=args.merge_all_iters_to_one_epoch
  File "/home/mi/GLENet/tools/train_utils/train_utils.py", line 140, in train_model
    dataloader_iter=dataloader_iter
  File "/home/mi/GLENet/tools/train_utils/train_utils.py", line 47, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "../pcdet/models/__init__.py", line 42, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/home/mi/miniconda3/envs/pcdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "../pcdet/models/detectors/voxel_rcnn.py", line 14, in forward
    loss, tb_dict, disp_dict = self.get_training_loss()
  File "../pcdet/models/detectors/voxel_rcnn.py", line 29, in get_training_loss
    loss_rcnn, tb_dict = self.roi_head.get_loss(tb_dict)
  File "../pcdet/models/roi_heads/roi_head_template.py", line 281, in get_loss
    rcnn_loss_reg, reg_tb_dict = self.get_box_reg_layer_loss(self.forward_ret_dict)
  File "../pcdet/models/roi_heads/voxelrcnn_kl_label_iou_head.py", line 105, in get_box_reg_layer_loss
    label_var_log = torch.log(gt_uncertaintys_of_rois + 1e-10)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

I wonder why gt_ uncertaintys_ of_ rois returns a none value

**Comment by Eaphan** [comment]
Please make sure that you install the GLENet and prepare data as I described in readme file.

**Comment by jamesheatonrdm** [comment]
I get the same error. I am using KITTI dataset and followed the instructions in the README

**Comment by jamesheatonrdm** [comment]
Managed to solve by viewing support on the first issue

**Comment by ajou-sh** [comment]
I have same issue. how to I fix it? please give me a answer.

In 'kitti_dbinfos_train_wconf_v4.pkl', there have uncertainty value each other. but gt_ uncertaintys_ of_ rois returns none value

**Comment by Eaphan** [comment]
Do you follow the instructions in the "[Generate Label Uncertainty with GLEnet](https://github.com/Eaphan/GLENet#generate-label-uncertainty-with-glenet)" part of README.md.

Please rename the provided files:
kitti_infos_train_wconf_v5.pkl -> kitti_infos_train.pkl 
kitti_dbinfos_train_wconf_v5.pkl -> kitti_dbinfos_train.pkl

**Comment by ajou-sh** [comment]
I changed it as you said and it was resolved. thank you!
